#Config File example
save_dir: /content/drive/MyDrive/workspace/owndata/ELG4960_Out/2/nanodet-m_autoaug_debug_verify
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    img_path: /content/drive/MyDrive/ELG4960_Out/2/train/
    ann_path: /content/drive/MyDrive/ELG4960_Out/2/train/annotations.json
    input_size: [1024,96] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
#      brightness: 0.2
#      contrast: [0.8, 1.2]
#      saturation: [0.8, 1.2]
      autoaug_value: {'a1': 0.38901975750923157,
 'a10': 0.7701295018196106,
 'a11': -0.06382465362548828,
 'a2': 0.07353256642818451,
 'a3': -0.06273103505373001,
 'a4': 1.193111777305603,
 'a5': 0.20649823546409607,
 'a6': -0.799005389213562,
 'a7': 0.07718230783939362,
 'a8': -0.5927864909172058,
 'a9': 0.2556118369102478,
 'b0': 0.25739431381225586,
 'b1': -0.03339933231472969,
 'b10': -0.3790638744831085,
 'b11': 0.30356529355049133,
 'b2': -0.013478205539286137,
 'b3': 0.3427799344062805,
 'b4': -0.6484463214874268,
 'b5': 0.04032512009143829,
 'b6': 0.809535026550293,
 'b7': 0.04320482164621353,
 'b8': 0.640312671661377,
 'b9': -0.22022654116153717}
      normalize: [[127.0], [128.0]]
  val:
    name: coco
    img_path: /content/drive/MyDrive/ELG4960_Out/2/valid/
    ann_path: /content/drive/MyDrive/ELG4960_Out/2/valid/annotations.json
    input_size: [1024,96] #[w,h]
    keep_ratio: True
    pipeline:
      autoaug_value: {'a1': 0.38901975750923157,
 'a10': 0.7701295018196106,
 'a11': -0.06382465362548828,
 'a2': 0.07353256642818451,
 'a3': -0.06273103505373001,
 'a4': 1.193111777305603,
 'a5': 0.20649823546409607,
 'a6': -0.799005389213562,
 'a7': 0.07718230783939362,
 'a8': -0.5927864909172058,
 'a9': 0.2556118369102478,
 'b0': 0.25739431381225586,
 'b1': -0.03339933231472969,
 'b10': -0.3790638744831085,
 'b11': 0.30356529355049133,
 'b2': -0.013478205539286137,
 'b3': 0.3427799344062805,
 'b4': -0.6484463214874268,
 'b5': 0.04032512009143829,
 'b6': 0.809535026550293,
 'b7': 0.04320482164621353,
 'b8': 0.640312671661377,
 'b9': -0.22022654116153717}
      normalize: [[127.0], [128.0]]
device:
  gpu_ids: [0]
  workers_per_gpu: 2
  batchsize_per_gpu: 30
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 3000
    ratio: 0.01
  total_epochs: 500
  lr_schedule:
    name: MultiStepLR
    milestones: [300,400,450,475]
    gamma: 0.1
  val_intervals: 20
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 20

class_names: ['defect']
