#Config File example
save_dir: /content/drive/MyDrive/workspace/owndata/MF630F_Out/2/nanodet-m_mobnet/1_2_4_6
model:
  arch:
    name: OneStageDetector
    backbone:
      name: MobileNetV2

      out_stages: [1,2,4,6]
      act: ReLU
    fpn:
      name: PAN
      in_channels: [24, 32, 96, 1280]
      out_channels: 96
      start_level: 0
      num_outs: 4
    head:
      name: NanoDetHead
      num_classes: 1
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [4, 8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: coco
    img_path: /content/drive/MyDrive/MF630F_Out/2/train/
    ann_path: /content/drive/MyDrive/MF630F_Out/2/train/annotations.json
    input_size: [1024,96] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
#      brightness: 0.2
#      contrast: [0.8, 1.2]
#      saturation: [0.8, 1.2]
      normalize: [[127.0], [128.0]]
  val:
    name: coco
    img_path: /content/drive/MyDrive/MF630F_Out/2/valid/
    ann_path: /content/drive/MyDrive/MF630F_Out/2/valid/annotations.json
    input_size: [1024,96] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[127.0], [128.0]]
device:
  gpu_ids: [0]
  workers_per_gpu: 2
  batchsize_per_gpu: 30
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 3000
    ratio: 0.01
  total_epochs: 500
  lr_schedule:
    name: MultiStepLR
    milestones: [300,400,450,475]
    gamma: 0.1
  val_intervals: 20
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 20

class_names: ['defect']
